config/routes.rb
Rails.application.routes.draw do
  resources :offices
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_one :office, dependent: :destroy
end

app/models/office.rb
class Office < ApplicationRecord
  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_path, notice: "Employee was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.expect(employee: [ :name ])
    end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: %i[ show edit update destroy ]

  # GET /offices or /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1 or /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices or /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: "Office was successfully created." }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1 or /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: "Office was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1 or /offices/1.json
  def destroy
    @office.destroy!

    respond_to do |format|
      format.html { redirect_to offices_path, notice: "Office was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def office_params
      params.expect(office: [ :number, :employee_id ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>Name:</strong>
    <%= employee.name %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<% content_for :title, "Editing employee" %>

<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Employees" %>

<h1>Employees</h1>

<div id="employees">
  <% @employees.each do |employee| %>
    <%= render employee %>
    <p>
      <%= link_to "Show this employee", employee %>
    </p>
  <% end %>
</div>

<%= link_to "New employee", new_employee_path %>

app/views/employees/new.html.erb
<% content_for :title, "New employee" %>

<h1>New employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Office Employee App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/offices/_form.html.erb
<%= form_with(model: office) do |form| %>
  <% if office.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
        <% office.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :employee_id, style: "display: block" %>
    <%= form.text_field :employee_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/offices/_office.html.erb
<div id="<%= dom_id office %>">
  <p>
    <strong>Number:</strong>
    <%= office.number %>
  </p>

  <p>
    <strong>Employee:</strong>
    <%= office.employee_id %>
  </p>

</div>

app/views/offices/edit.html.erb
<% content_for :title, "Editing office" %>

<h1>Editing office</h1>

<%= render "form", office: @office %>

<br>

<div>
  <%= link_to "Show this office", @office %> |
  <%= link_to "Back to offices", offices_path %>
</div>

app/views/offices/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Offices" %>

<h1>Offices</h1>


<div id="offices">
  <% @offices.each do |office| %>
    <p>
      <strong>Number:</strong> <%= office.number %><br>
      <strong>Employee:</strong> <%= office.employee.name if office.employee %><br>
      <%= link_to "Show this office", office %>
    </p>
  <% end %>
</div>

<%= link_to "New office", new_office_path %>

app/views/offices/new.html.erb
<% content_for :title, "New office" %>

<h1>New office</h1>

<%= render "form", office: @office %>

<br>

<div>
  <%= link_to "Back to offices", offices_path %>
</div>

app/views/offices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @office %>

<div>
  <%= link_to "Edit this office", edit_office_path(@office) %> |
  <%= link_to "Back to offices", offices_path %>

  <%= button_to "Destroy this office", @office, method: :delete %>
</div>